import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readdir,readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {planFor,stockView,requireUser,quoteNeedsRefresh} from '../server/cloud.mjs';
import {subscriptionEntitlement} from '../server/billing.mjs';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',C='33333333-3333-4333-8333-333333333333';
let db;
const quote=symbol=>({symbol,companyName:symbol+' Company',currency:'USD',price:100,exchange:'Nasdaq',quoteTime:'2026-09-04T20:00:00.000Z',checkedAt:'2026-09-04T20:01:00.000Z'});
async function list(user){return (await db.query('select id from wl_watchlists where owner_id=$1 order by created_at,id',[user])).rows[0].id;}
async function action(user,action,listId=null,name=null,symbol=null,stock=null,token=null){return db.query('select wl_account_action($1,$2,$3,$4,$5,$6,$7,$8)',[user,action,listId,name,symbol,symbol?JSON.stringify(quote(symbol)):null,stock,token]);}
before(async()=>{db=new PGlite();await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated;`);for(const file of (await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile('supabase/migrations/'+file,'utf8'));await db.query('insert into auth.users values($1),($2),($3)',[A,B,C]);for(const id of [A,B,C])await db.query('select wl_ensure_profile($1,$2,0)',[id,'Test member']);});
after(async()=>{await db?.close();});
test('anonymous API access is rejected before any database operation',async()=>{await assert.rejects(requireUser(new Request('http://localhost/api/watchlists')),e=>e.status===401);});
test('database migration enforces five lists and twenty stocks',async()=>{const id=await list(A);for(let i=1;i<5;i++)await action(A,'createList',null,'List '+i);await assert.rejects(action(A,'createList',null,'Extra'),/limit reached/);for(let i=0;i<20;i++)await action(A,'addStock',id,null,'S'+i);await assert.rejects(action(A,'addStock',id,null,'TWENTYONE'),/Stock limit reached/);});
test('non-owner cannot rename, delete, add, remove, share, or revoke',async()=>{const target=await list(A);const stock=(await db.query('select id from wl_stocks where watchlist_id=$1 limit 1',[target])).rows[0].id;for(const op of ['renameList','deleteList','addStock','removeStock','shareList','revokeShare'])await assert.rejects(action(B,op,target,'Intrusion','EVIL',stock,'x'.repeat(43)),/do not own/);assert.equal((await db.query('select count(*)::int n from wl_stocks where watchlist_id=$1',[target])).rows[0].n,20);});
test('RLS hides another account and denies direct writes and privileged RPCs',async()=>{await db.exec('set role authenticated');try{await db.query("select set_config('request.jwt.claim.sub',$1,false)",[B]);const visible=await db.query('select owner_id from wl_watchlists');assert.ok(visible.rows.length>0);assert.ok(visible.rows.every(l=>l.owner_id===B));assert.equal((await db.query('select * from wl_stocks')).rows.length,0);await assert.rejects(db.query('update wl_profiles set subscription_status=\'active\' where id=$1',[B]),/permission denied/);await assert.rejects(db.query("select wl_account_action($1,'createList',null,'Hack')",[B]),/permission denied/);await assert.rejects(db.query('select * from wl_quotes'),/permission denied/);}finally{await db.exec('reset role');}await db.exec('set role anon');try{await assert.rejects(db.query('select * from wl_watchlists'),/permission denied/);}finally{await db.exec('reset role');}});
test('every account has the same five-list and twenty-stock cap',async()=>{for(let i=1;i<5;i++)await action(B,'createList',null,'List '+i);await assert.rejects(action(B,'createList',null,'List six'),/limit reached/);const id=await list(B);for(let i=0;i<20;i++)await action(B,'addStock',id,null,'P'+i);await assert.rejects(action(B,'addStock',id,null,'TWENTYONE'),/Stock limit reached/);});
test('sharing is stable until revoked; rotation invalidates the old capability',async()=>{const id=await list(A);await action(A,'shareList',id,null,null,null,'a'.repeat(43));await action(A,'shareList',id,null,null,null,'b'.repeat(43));assert.equal((await db.query('select share_token from wl_watchlists where id=$1',[id])).rows[0].share_token,'a'.repeat(43));await action(A,'revokeShare',id);assert.equal((await db.query('select share_token from wl_watchlists where id=$1',[id])).rows[0].share_token,null);await action(A,'shareList',id,null,null,null,'b'.repeat(43));assert.equal((await db.query('select count(*)::int n from wl_watchlists where share_token=$1',['a'.repeat(43)])).rows[0].n,0);});
test('trial expiry does not block additions',async()=>{const id=await list(A);const stock=(await db.query('select id from wl_stocks where watchlist_id=$1 limit 1',[id])).rows[0].id;await action(A,'removeStock',id,null,null,stock);await db.query("update wl_profiles set trial_ends_at=now()-interval '1 day' where id=$1",[A]);await action(A,'addStock',id,null,'NEW');assert.equal((await db.query('select count(*)::int n from wl_stocks where watchlist_id=$1',[id])).rows[0].n,20);});
test('every extra list can accept stocks up to the same cap',async()=>{const lists=(await db.query('select id from wl_watchlists where owner_id=$1 order by created_at,id',[B])).rows;assert.equal(lists.length,5);await action(B,'addStock',lists[1].id,null,'NEW');assert.equal((await db.query('select count(*)::int n from wl_stocks where watchlist_id=$1',[lists[0].id])).rows[0].n,20);});
test('community counts distinct members and shows every country with a recorded user',async()=>{await db.query("select wl_country($1,'US')",[A]);await db.query("select wl_country($1,'US')",[B]);let stats=(await db.query('select wl_community() as stats')).rows[0].stats;assert.equal(stats.users,3);assert.deepEqual(stats.countries,[{code:'US',users:2}]);await db.query("select wl_country($1,'US')",[C]);stats=(await db.query('select wl_community() as stats')).rows[0].stats;assert.deepEqual(stats.countries,[{code:'US',users:3}]);await db.query('select wl_country($1,null)',[C]);assert.deepEqual((await db.query('select wl_community() as stats')).rows[0].stats.countries,[{code:'US',users:2}]);});
test('duplicate and older Stripe deliveries do not undo the latest entitlement',async()=>{await db.query("update wl_profiles set stripe_customer_id='cus_test' where id=$1",[C]);await db.query('select wl_apply_billing($1,$2,$3,$4,$5,$6)',[C,'cus_test','active','2099-01-01','2026-09-05T02:00:00Z','evt_new']);await db.query('select wl_apply_billing($1,$2,$3,$4,$5,$6)',[C,'cus_test','free',null,'2026-09-05T01:00:00Z','evt_old']);await db.query('select wl_apply_billing($1,$2,$3,$4,$5,$6)',[C,'cus_test','free',null,'2026-09-05T03:00:00Z','evt_new']);assert.equal((await db.query('select wl_is_pro($1) pro',[C])).rows[0].pro,true);});
test('rate limit survives independent calls',async()=>{assert.equal((await db.query("select wl_rate('test',2,60) ok")).rows[0].ok,true);assert.equal((await db.query("select wl_rate('test',2,60) ok")).rows[0].ok,true);assert.equal((await db.query("select wl_rate('test',2,60) ok")).rows[0].ok,false);});
test('plan limits ignore Stripe status',()=>{const make=(status,price,until)=>({status,items:{data:[{price:{id:price},current_period_end:until}]}});const now=1000000;assert.deepEqual(subscriptionEntitlement([make('active','price_other',2000),make('past_due','price_pro',2000),make('trialing','price_pro',2000),make('active','price_pro',500)],'price_pro',now),{status:'free',until:null});assert.equal(subscriptionEntitlement([make('active','price_pro',2000)],'price_pro',now).status,'active');assert.equal(planFor({subscription_status:'active',pro_until:'2099-01-01',trial_ends_at:null}).maxLists,5);assert.equal(planFor({}).maxStocks,20);});
test('fresh quotes never overwrite baseline or mix currency',()=>{const stock={id:'stock',symbol:'TEST',added_at:'2026-09-04T20:01:00Z',snapshot:quote('TEST')};const updated=stockView(stock,{quote:{...quote('TEST'),price:125,previousClose:120,changePercent:4.1667}});assert.equal(updated.addedPrice,100);assert.equal(updated.currentPrice,125);assert.equal(updated.dayChangePercent,4.1667);assert.equal(updated.previousClose,120);assert.equal(stockView(stock,{quote:{...quote('TEST'),price:125,currency:'EUR',previousClose:130,changePercent:1}}).currentPrice,100);assert.equal(stockView(stock,{quote:{...quote('TEST'),price:125,currency:'EUR'}}).dayChangePercent,null);});
test('cached quotes older than a minute are treated as stale',()=>{
  const now=Date.parse('2026-09-23T17:52:00Z');
  assert.equal(quoteNeedsRefresh(undefined,now),true);
  assert.equal(quoteNeedsRefresh({fetched_at:'2026-09-23T17:51:30Z'},now),false);
  assert.equal(quoteNeedsRefresh({fetched_at:'2026-09-21T18:27:00Z'},now),true);
});
test('advanced add works without a paid plan and rejects invalid positions',async()=>{const id=await list(C);await db.query("select wl_advanced_action($1,'convertList',$2)",[C,id]);assert.equal((await db.query('select mode from wl_watchlists where id=$1',[id])).rows[0].mode,'advanced');await assert.rejects(db.query("select wl_advanced_action($1,'addStock',$2,p_symbol=>'ADV',p_quote=>$3,p_quantity=>-1,p_cost=>10,p_acquired=>now())",[C,id,JSON.stringify(quote('ADV'))]),/positive/);await db.query("select wl_advanced_action($1,'addStock',$2,p_symbol=>'ADV',p_quote=>$3,p_quantity=>100,p_cost=>50,p_acquired=>'2023-01-03')",[C,id,JSON.stringify(quote('ADV'))]);const row=(await db.query('select * from wl_stocks where watchlist_id=$1',[id])).rows[0];assert.equal(Number(row.quantity),100);assert.equal(row.snapshot.price,100);await assert.rejects(db.query("select wl_advanced_action($1,'updatePosition',$2,p_stock=>$3,p_quantity=>20,p_cost=>10,p_acquired=>now())",[A,id,row.id]),/do not own/);await assert.rejects(db.query("select wl_advanced_action($1,'updatePosition',$2,p_stock=>$3,p_quantity=>20,p_cost=>10,p_acquired=>now())",[C,id,row.id]),/fixed after adding/);});
