'use client';
import {useEffect,useRef,useState} from 'react';
import {useT} from './language';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {price,type Stock,type Watchlist} from '@/lib/watchlist';
import {marketChart} from '@/lib/market';
import {parseImport,scenario,benchmarkRace,makeCheckpoint} from '@/lib/idea-lab.mjs';
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const percent=(n:number)=>`${n>0?'+':''}${n.toFixed(2)}%`;
function StockSelect({stocks,value,onChange}:{stocks:Stock[];value:string;onChange:(v:string)=>void}){const t=useT();return <label>{t('Stock')}<select value={value} onChange={e=>onChange(e.target.value)}>{stocks.map(s=><option key={s.id} value={s.symbol}>{s.symbol} · {s.companyName}</option>)}</select></label>;}
type Props={list:Watchlist;userId:string;maxStocks:number;canEdit:boolean;busy:boolean;onAdd:(symbol:string)=>Promise<unknown>;onBusy:(busy:boolean)=>void};
export function IdeaLab(props:Props){
 const t=useT();const [tab,setTab]=useState('import'),[importing,setImporting]=useState(false);
 const tabs=[['import','Bring your watchlist'],['journal','Decision checkpoints'],['benchmark','Idea vs. benchmark'],['scenario','Scenario lab']];
 return <section className="idea-lab" aria-label={t('Idea lab')}><header><p className="eyebrow">{t('FROM WATCHING TO LEARNING')}</p><h3>{t('Idea lab')}</h3><p>{t('Bring your ideas, record your reasoning, and test the numbers.')}</p></header><fieldset className="idea-tabs" aria-label={t('Idea lab tools')}>{tabs.map(([id,label])=><Button key={id} variant={tab===id?'secondary':'outline'} aria-pressed={tab===id} disabled={importing} onClick={()=>setTab(id)}>{t(label)}</Button>)}</fieldset>
 {tab==='import'?<ImportPanel {...props} onBusy={value=>{setImporting(value);props.onBusy(value);}}/>:!props.list.stocks.length?<p>{t('Add a stock to use this tool.')}</p>:tab==='journal'?<Journal key={props.userId+props.list.id} list={props.list} userId={props.userId}/>:tab==='benchmark'?<Benchmark key={props.list.id} stocks={props.list.stocks}/>:<Scenario key={props.list.id} stocks={props.list.stocks}/>}
 </section>;
}
function ImportPanel({list,maxStocks,canEdit,busy,onAdd,onBusy}:Props){
 const t=useT();const [text,setText]=useState(''),[preview,setPreview]=useState<ReturnType<typeof parseImport>>([]),[error,setError]=useState(''),[running,setRunning]=useState(false),[results,setResults]=useState<{symbol:string;message:string}[]>([]);const stop=useRef(false),working=useRef(false);
 useEffect(()=>()=>{stop.current=true;},[]);
 function inspect(){try{setPreview(parseImport(text,list.stocks.map(s=>s.symbol),Math.max(0,maxStocks-list.stocks.length)));setResults([]);setError('');}catch(e){setError((e as Error).message);setPreview([]);}}
 async function run(){if(working.current||busy||!canEdit)return;working.current=true;stop.current=false;setRunning(true);onBusy(true);setResults([]);try{const rows=parseImport(text,list.stocks.map(s=>s.symbol),Math.max(0,maxStocks-list.stocks.length));for(const row of rows.filter(r=>!r.reason)){if(stop.current)break;try{await onAdd(row.symbol);setResults(prev=>[...prev,{symbol:row.symbol,message:'Added'}]);}catch(e){setResults(prev=>[...prev,{symbol:row.symbol,message:(e as Error).message}]);}}}catch(e){setError((e as Error).message);}finally{working.current=false;setRunning(false);onBusy(false);setPreview([]);}}
 return <div className="idea-panel"><h4>{t('Bring your watchlist')}</h4><p>{t('Paste tickers, a TradingView text export, or a CSV with a Ticker or Symbol column.')}</p><p className="field-note">{t('Imports symbols only. Starting prices are recorded now; quantities, costs and historical returns are not imported. Each quote must match this list’s currency.')}</p>
 <label>{t('Ticker list or CSV')}<textarea rows={4} maxLength={100000} disabled={running||!canEdit} value={text} onChange={e=>{setText(e.target.value);setPreview([]);}} placeholder={'NASDAQ:AAPL, NASDAQ:MSFT\nNYSE:V'}/></label>
 <label>{t('Choose CSV or TXT file')}<input type="file" accept=".csv,.txt,text/plain,text/csv" disabled={running||!canEdit} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>100000){setError(t('Use a file smaller than 100 KB.'));return;}try{setText(await f.text());setPreview([]);setError('');}catch{setError(t('File could not be read.'));}}}/></label>
 <div className="idea-actions"><Button variant="outline" disabled={!canEdit||running||!text.trim()} onClick={inspect}>{t('Preview import')}</Button>{preview.some(r=>!r.reason)&&<Button disabled={running||busy} onClick={()=>void run()}>{t('Import selected tickers')} ({preview.filter(r=>!r.reason).length})</Button>}{running&&<Button variant="outline" onClick={()=>{stop.current=true;}}>{t('Stop after current stock')}</Button>}</div>
 {!canEdit&&<p>{t('Only the owner can import stocks.')}</p>}{error&&<p role="alert" className="form-error">{t(error)}</p>}
 {!!preview.length&&<ul className="idea-preview">{preview.map((row,i)=><li key={i}><strong>{row.symbol}</strong><span>{t(row.reason||'Ready to import')}</span></li>)}</ul>}
 <div aria-live="polite">{running&&<p>{t('Importing one stock at a time…')}</p>}{results.map(row=><p key={row.symbol}><strong>{row.symbol}</strong> · {t(row.message)}</p>)}</div>
 </div>;
}
type Checkpoint=ReturnType<typeof makeCheckpoint>;
function Journal({list,userId}:{list:Watchlist;userId:string}){
 const t=useT();const [symbol,setSymbol]=useState(list.stocks[0].symbol),[thesis,setThesis]=useState(''),[invalidation,setInvalidation]=useState(''),[review,setReview]=useState(''),[entries,setEntries]=useState<Checkpoint[]>([]),[error,setError]=useState(''),[ready,setReady]=useState(false),[removing,setRemoving]=useState('');
 const key='watchlist:checkpoints:v1:'+userId+':'+list.id;
 useEffect(()=>{const timer=setTimeout(()=>{try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))setEntries(saved.filter(e=>e&&typeof e.symbol==='string'&&typeof e.thesis==='string'&&Number.isFinite(e.price)&&e.price>0&&typeof e.reviewDate==='string'&&typeof e.createdAt==='string').slice(0,100));setReady(true);}catch{setError('Saved checkpoints could not be read.');}},0);return()=>clearTimeout(timer);},[key]);
 function save(e:{preventDefault:()=>void}){e.preventDefault();try{if(entries.length>=100)throw Error('This notebook is full. Export a backup before removing entries.');const stock=list.stocks.find(s=>s.symbol===symbol);const entry=makeCheckpoint({stock,thesis,invalidation,reviewDate:review});const next=[entry,...entries];localStorage.setItem(key,JSON.stringify(next));setEntries(next);setThesis('');setInvalidation('');setError('');}catch(e){setError((e as Error).message);}}
 return <div className="idea-panel"><h4>{t('Decision checkpoints')}</h4><p>{t('Record why you are watching, what would change your mind, and when to review it. Each checkpoint keeps its original price and timestamp.')}</p><p className="field-note">{t('Private to this browser. Checkpoints do not sync to your account or appear in shared watchlists. Export a backup to keep a copy.')}</p><form onSubmit={save}><div className="idea-fields"><StockSelect stocks={list.stocks} value={symbol} onChange={setSymbol}/><label>{t('Review date')}<Input required type="date" value={review} min={new Date().toISOString().slice(0,10)} onChange={e=>setReview(e.target.value)}/></label></div><div className="idea-actions">{[7,30].map(days=><Button key={days} type="button" variant="outline" onClick={()=>{const date=new Date();date.setUTCDate(date.getUTCDate()+days);setReview(date.toISOString().slice(0,10));}}>{t(days===7?'Review in 7 days':'Review in 30 days')}</Button>)}</div><label>{t('Why am I watching this?')}<textarea required rows={2} maxLength={500} value={thesis} onChange={e=>setThesis(e.target.value)}/></label><label>{t('What would change my mind?')}<textarea required rows={2} maxLength={500} value={invalidation} onChange={e=>setInvalidation(e.target.value)}/></label><div className="idea-actions"><Button disabled={!ready} type="submit">{t('Save checkpoint')}</Button><Button type="button" variant="outline" disabled={!entries.length} onClick={()=>download(entries,'decision-checkpoints.json')}>{t('Export checkpoints')}</Button></div></form>{error&&<p role="alert" className="form-error">{t(error)}</p>}
 <div className="checkpoint-list">{entries.map(entry=>{const stock=list.stocks.find(s=>s.symbol===entry.symbol&&s.currency===entry.currency);const change=stock?(stock.currentPrice/entry.price-1)*100:null;return <article key={entry.id}><header><strong>{entry.symbol}</strong><span>{entry.reviewDate<=new Date().toISOString().slice(0,10)?t('Review due'):t('Review date')} · {entry.reviewDate}</span></header><small>{new Date(entry.createdAt).toLocaleString()} · {price(entry.price,entry.currency)} {t('at checkpoint')}</small><p>{entry.thesis}</p><p><strong>{t('Reconsider if')}</strong> · {entry.invalidation}</p><p>{t('Price change since checkpoint')}: {change===null?'—':percent(change)}{stock?.quoteError?' · '+t('Previous quote'):''}</p><Button variant="ghost" onClick={()=>{if(removing!==entry.id){setRemoving(entry.id);return;}try{const next=entries.filter(e=>e.id!==entry.id);localStorage.setItem(key,JSON.stringify(next));setEntries(next);}catch{setError(t('Checkpoint could not be removed.'));}}}>{t(removing===entry.id?'Confirm removal':'Remove checkpoint')}</Button>{removing===entry.id&&<Button variant="ghost" onClick={()=>setRemoving('')}>{t('Cancel')}</Button>}</article>;})}</div></div>;
}
function Benchmark({stocks}:{stocks:Stock[]}){
 const t=useT();const [symbol,setSymbol]=useState(stocks[0].symbol),[benchmark,setBenchmark]=useState('SPY'),[result,setResult]=useState<ReturnType<typeof benchmarkRace>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const generation=useRef(0);useEffect(()=>()=>{generation.current++;},[]);
 const stock=stocks.find(s=>s.symbol===symbol)||stocks[0];
 async function run(){const token=++generation.current;setBusy(true);setError('');setResult(null);try{const [a,b]=await Promise.all([marketChart(stock.symbol,'5y'),marketChart(benchmark,'5y')]);const next=benchmarkRace(a,b,stock.addedAt);if(token===generation.current)setResult(next);}catch(e){if(token===generation.current)setError((e as Error).message);}finally{if(token===generation.current)setBusy(false);}}
 return <div className="idea-panel"><h4>{t('Idea vs. benchmark')}</h4><p>{t('Did this idea outperform a broad ETF over the same trading days? Compare price returns from the first shared daily price on or after you added it.')}</p><div className="idea-fields"><StockSelect stocks={stocks} value={symbol} onChange={v=>{setSymbol(v);setResult(null);setError('');generation.current++;setBusy(false);}}/><label>{t('Benchmark ETF')}<select value={benchmark} onChange={e=>{setBenchmark(e.target.value);setResult(null);setError('');generation.current++;setBusy(false);}}><option value="SPY">SPY · S&P 500 · USD</option><option value="QQQ">QQQ · Nasdaq-100 · USD</option><option value="VT">VT · Global equities · USD</option><option value="XIU.TO">XIU.TO · Canada · CAD</option><option value="EXSA.DE">EXSA.DE · Europe · EUR</option></select></label></div><Button disabled={busy} onClick={()=>void run()}>{busy?t('Comparing…'):t('Compare this idea')}</Button>{error&&<p role="alert" className="form-error">{t(error)}</p>}
 {result&&<div className="idea-race" aria-live="polite"><p>{result.start} → {result.end}</p><div className="idea-metrics"><div><span>{stock.symbol}</span><strong>{percent(result.stockReturn)}</strong></div><div><span>{benchmark}</span><strong>{percent(result.benchmarkReturn)}</strong></div><div><span>{t('Difference (percentage points)')}</span><strong>{result.excess>0?'+':''}{result.excess.toFixed(2)}</strong></div></div><p>{t('If both started at 100')}: {stock.symbol} {(100+result.stockReturn).toFixed(2)} · {benchmark} {(100+result.benchmarkReturn).toFixed(2)}</p></div>}
 <p className="field-note">{t('Daily-price comparison, not your purchase return. The latest session may be incomplete. Excludes dividends, fees and currency conversion. Requires two common trading days and up to five years of history.')}</p></div>;
}
function Scenario({stocks}:{stocks:Stock[]}){
 const t=useT();const [budget,setBudget]=useState('10000'),[mode,setMode]=useState('equal'),[shocks,setShocks]=useState<Record<string,string>>({});let result:ReturnType<typeof scenario>|null=null,error='';try{result=scenario(stocks,Number(budget),shocks,mode);}catch(e){error=(e as Error).message;}
 return <div className="idea-panel"><h4>{t('Scenario lab')}</h4><p>{t('Test a hypothetical move in each stock before risking money. This calculator never changes your holdings.')}</p><div className="idea-fields"><label>{t('Hypothetical budget')} · {stocks[0]?.currency}<Input type="number" min="0.01" step="any" value={budget} onChange={e=>setBudget(e.target.value)}/></label><label>{t('Allocation method')}<select value={mode} onChange={e=>setMode(e.target.value)}><option value="equal">{t('Equal weights')}</option><option value="holdings">{t('Use current holding weights')}</option></select></label></div><div className="idea-actions">{[-20,-10,10].map(n=><Button key={n} variant="outline" onClick={()=>setShocks(Object.fromEntries(stocks.map(s=>[s.symbol,String(n)])))}>{t('All stocks')} {n>0?'+':''}{n}%</Button>)}<Button variant="ghost" onClick={()=>setShocks({})}>{t('Reset scenario')}</Button></div><div className="scenario-stocks">{stocks.map(s=><label key={s.id}>{s.symbol} · {t('Hypothetical move (%)')}<Input type="number" min="-100" max="1000" step="any" value={shocks[s.symbol]??'0'} onChange={e=>setShocks(prev=>({...prev,[s.symbol]:e.target.value}))}/></label>)}</div>{error&&<p role="alert" className="form-error">{t(error)}</p>}
 {result&&<div aria-live="polite"><div className="idea-metrics"><div><span>{t('Hypothetical ending value')}</span><strong>{price(result.end,result.currency)}</strong></div><div><span>{t('Hypothetical change')}</span><strong>{price(result.impact,result.currency)}</strong><small>{percent(result.change)}</small></div></div><ul className="idea-preview">{[...result.rows].sort((a,b)=>a.impact-b.impact).map(row=><li key={row.symbol}><strong>{row.symbol} · {(row.weight*100).toFixed(1)}%</strong><span>{price(row.impact,result!.currency)}</span></li>)}</ul></div>}
 <p className="field-note">{t('Your assumptions, not a forecast. Uses the displayed prices and excludes fees, dividends, taxes and currency conversion.')}</p></div>;
}
