 'use client';
import {T} from '@/components/product/language';
import {useEffect,useState,useId} from 'react';
import {Area,CartesianGrid,Line,ComposedChart,XAxis,YAxis,Tooltip} from 'recharts';
import {ChartContainer} from '@/components/ui/chart';
import {Button} from '@/components/ui/button';
import {apiFetch} from '@/lib/auth-client';
import {price,type Watchlist} from '@/lib/watchlist';
import {rangeLabel,seriesPeriodStats} from '@/lib/chart-period.mjs';
type History={range:string;points:{time:number;value:number;cost:number;gain:number}[];method:string;asOf:string};
export function PortfolioHistoryChart({chart}:{chart:Pick<History,'points'>}){
 const id=useId().replace(/:/g,'');
 const label=(v:number)=>new Date(v).toLocaleDateString(undefined,{timeZone:'UTC',month:'short',day:'numeric',year:'2-digit'});
 // Extend a single daily snapshot across its day for display only; keep API history unchanged.
 const displayPoints=chart.points.length===1?[{...chart.points[0],time:chart.points[0].time-43200000},{...chart.points[0],time:chart.points[0].time+43200000}]:chart.points;
 return <ChartContainer className="portfolio-chart" config={{value:{label:'Market value',color:'#315ce8'},cost:{label:'Invested capital',color:'#94a3b8'}}}><ComposedChart accessibilityLayer data={displayPoints} margin={{top:12,right:12,left:6,bottom:4}}><defs><linearGradient id={'portfolio-'+id} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#315ce8" stopOpacity={.2}/><stop offset="1" stopColor="#315ce8" stopOpacity={.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e7edf3"/><XAxis dataKey="time" type="number" scale="time" domain={chart.points.length===1?[chart.points[0].time-43200000,chart.points[0].time+43200000]:['dataMin','dataMax']} ticks={chart.points.filter((_,i,points)=>i===0||i===points.length-1||i%Math.max(1,Math.ceil(points.length/4))===0).map(p=>p.time)} tickFormatter={label} minTickGap={65} tickLine={false}/><YAxis domain={[0,'auto']} width={90} tickFormatter={v=>price(Number(v),'USD')} tickLine={false}/><Tooltip labelFormatter={v=>label(chart.points.length===1?chart.points[0].time:Number(v))} formatter={(v,n)=>[price(Number(v),'USD'),n==='value'?'Market value':'Invested capital']}/><Area type="linear" dataKey="value" dot={false} stroke="#315ce8" fill={`url(#portfolio-${id})`} isAnimationActive={false}/><Line type="stepAfter" dataKey="cost" stroke="#94a3b8" strokeDasharray="5 4" dot={false} isAnimationActive={false}/></ComposedChart></ChartContainer>;
}
export function Portfolio({list,version,shareToken,guest}:{list:Watchlist;version:string;shareToken?:string;guest?:boolean}){
 const [retry,setRetry]=useState(0);const [range,setRange]=useState('1mo'),[chart,setChart]=useState<History|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const holdings=list.stocks.filter(s=>s.quantity&&s.costPerShare),cost=holdings.reduce((v,s)=>v+s.quantity!*s.costPerShare!,0),value=holdings.reduce((v,s)=>v+s.quantity!*s.currentPrice,0),gain=value-cost;
 useEffect(()=>{if(guest){setBusy(false);setChart(null);setError('');return;}let alive=true;setBusy(true);setChart(null);setError('');const request=(async()=>{const path=shareToken?`/api/share/${encodeURIComponent(shareToken)}/portfolio?range=${range}`:`/api/portfolio/${list.id}?range=${range}`;for(let attempt=0;attempt<2;attempt++){const response=await (shareToken?fetch(path):apiFetch(path));const contentType=response.headers.get('content-type')||'';if(!contentType.includes('application/json')){if(attempt===0&&[500,502,503,504].includes(response.status))continue;throw new Error('Portfolio history could not load. Please try again.');}const data=await response.json() as History&{error?:string};if(!response.ok)throw new Error(data.error||'Portfolio history unavailable.');return data;}throw new Error('Portfolio history could not load. Please try again.');})();void request.then(data=>{if(alive)setChart(data);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setBusy(false);});return()=>{alive=false;};},[list.id,range,version,shareToken,retry,guest]);
 const period=chart?seriesPeriodStats(chart.points):null;
 const periodLabel=rangeLabel(range);
 return <section className="portfolio-panel"><div className="portfolio-metrics"><div><span><T text="Portfolio value"/></span><strong>{price(value,'USD')}</strong></div><div><span><T text="Total cost"/></span><strong>{price(cost,'USD')}</strong></div><div><span><T text="Unrealized gain / loss"/></span><strong className={gain>=0?'up':'down'}>{gain>0?'+':''}{price(gain,'USD')}</strong><small className={gain>=0?'up':'down'}>{cost?`${gain>=0?'+':''}${(gain/cost*100).toFixed(2)}%`:'—'}</small></div><div><span><T text="Largest holding"/></span><strong>{[...holdings].sort((a,b)=>b.quantity!*b.currentPrice-a.quantity!*a.currentPrice)[0]?.symbol||'—'}</strong><small>{holdings.length} positions</small></div></div>
 {holdings.length<list.stocks.length&&<p className="quote-warning">{list.stocks.length-holdings.length} stocks need a share quantity and cost. The owner can set these legacy quantities once to include them in totals.</p>}
 <div className="portfolio-chart-heading"><div><h3><T text="Your portfolio over time"/></h3><p><T text="Market value and invested capital · USD"/></p></div><div className="range-buttons" aria-label="Portfolio chart range">{[['1mo','1M'],['3mo','3M'],['1y','1Y'],['5y','5Y'],['max','All']].map(([r,label])=><Button key={r} size="sm" variant={range===r?'secondary':'ghost'} aria-pressed={range===r} onClick={()=>setRange(r)}>{label}</Button>)}</div></div>
 {period&&period.changePercent!==null&&<div className={`chart-period-return ${period.up?'up':'down'}`} aria-live="polite"><strong>{`${period.up?'+':''}${period.changePercent.toFixed(2)}%`}</strong><span>{periodLabel} · {price(chart!.points[0].value,'USD')} → {price(chart!.points.at(-1)!.value,'USD')}</span></div>}
 {busy?<div className="chart-empty" role="status">Loading portfolio history…</div>:error?<div className="error-banner" role="alert">{error} <Button size="sm" variant="outline" onClick={()=>setRetry(v=>v+1)}>Try again</Button></div>:chart&&chart.points.length>0?<PortfolioHistoryChart chart={chart}/>:<div className="chart-empty">{guest?'Save your list to keep daily history on your account.':holdings.length?'Daily history starts on your purchase date. A trend appears after two days of data.':'Add shares and purchase costs to see your portfolio chart.'}</div>}

 {chart?.points.length===1&&<p className="portfolio-method">One daily snapshot · The flat line represents this day’s portfolio value.</p>}
 <p className="portfolio-method">{chart?.method||'Current holdings only. Excludes sold positions, dividends, fees and tax. Value changes can include added capital.'} {list.stocks.some(s=>s.quoteError)&&'Some current quotes are stale; last known prices are used.'}</p>
 {holdings.length>0&&<div className="allocation-strip" aria-label="Holding weights">{holdings.map(s=><span key={s.id}>{s.symbol} <strong>{value?((s.quantity!*s.currentPrice/value)*100).toFixed(1):'0'}%</strong></span>)}</div>}
 </section>;
}
