 'use client';
import {useEffect,useState,useId} from 'react';
import {Area,CartesianGrid,Line,ComposedChart,XAxis,YAxis,Tooltip} from 'recharts';
import {ChartContainer} from '@/components/ui/chart';
import {Button} from '@/components/ui/button';
import {apiJson} from '@/lib/auth-client';
import {price,type Watchlist} from '@/lib/watchlist';
type History={range:string;points:{time:number;value:number;cost:number;gain:number}[];method:string;asOf:string};
export function Portfolio({list,version,shareToken}:{list:Watchlist;version:string;shareToken?:string}){
 const [range,setRange]=useState('1mo'),[chart,setChart]=useState<History|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const id=useId().replace(/:/g,'');
 const holdings=list.stocks.filter(s=>s.quantity&&s.costPerShare),cost=holdings.reduce((v,s)=>v+s.quantity!*s.costPerShare!,0),value=holdings.reduce((v,s)=>v+s.quantity!*s.currentPrice,0),gain=value-cost;
 useEffect(()=>{let alive=true;setBusy(true);setChart(null);setError('');const request=shareToken?fetch(`/api/share/${encodeURIComponent(shareToken)}/portfolio?range=${range}`).then(async response=>{const data=await response.json() as History&{error?:string};if(!response.ok)throw new Error(data.error||'Portfolio history unavailable.');return data;}):apiJson<History>(`/api/portfolio/${list.id}?range=${range}`);void request.then(data=>{if(alive)setChart(data);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setBusy(false);});return()=>{alive=false;};},[list.id,range,version,shareToken]);
 const label=(v:number)=>new Date(v).toLocaleString(undefined,range==='1d'?{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}:{month:'short',day:'numeric',year:'2-digit'});
 return <section className="portfolio-panel"><div className="portfolio-metrics"><div><span>Portfolio value</span><strong>{price(value,'USD')}</strong></div><div><span>Total cost</span><strong>{price(cost,'USD')}</strong></div><div><span>Unrealized gain / loss</span><strong className={gain>=0?'up':'down'}>{gain>0?'+':''}{price(gain,'USD')}</strong><small className={gain>=0?'up':'down'}>{cost?`${gain>=0?'+':''}${(gain/cost*100).toFixed(2)}%`:'—'}</small></div><div><span>Largest holding</span><strong>{[...holdings].sort((a,b)=>b.quantity!*b.currentPrice-a.quantity!*a.currentPrice)[0]?.symbol||'—'}</strong><small>{holdings.length} positions</small></div></div>
 {holdings.length<list.stocks.length&&<p className="quote-warning">{list.stocks.length-holdings.length} stocks need a share quantity and cost. The owner can set these legacy quantities once to include them in totals.</p>}
 <div className="portfolio-chart-heading"><div><h3>Your portfolio over time</h3><p>Market value and invested capital · USD</p></div><div className="range-buttons" aria-label="Portfolio chart range">{[['1d','1D'],['1mo','1M'],['3mo','3M'],['1y','1Y'],['5y','5Y'],['max','All']].map(([r,label])=><Button key={r} size="sm" variant={range===r?'secondary':'ghost'} aria-pressed={range===r} onClick={()=>setRange(r)}>{label}</Button>)}</div></div>
 {busy?<div className="chart-empty" role="status">Loading portfolio history…</div>:error?<div className="error-banner" role="alert">{error}</div>:chart&&chart.points.length>1?<ChartContainer className="portfolio-chart" config={{value:{label:'Market value',color:'#315ce8'},cost:{label:'Invested capital',color:'#94a3b8'}}}><ComposedChart accessibilityLayer data={chart.points} margin={{top:12,right:12,left:6,bottom:4}}><defs><linearGradient id={'portfolio-'+id} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#315ce8" stopOpacity={.2}/><stop offset="1" stopColor="#315ce8" stopOpacity={.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e7edf3"/><XAxis dataKey="time" tickFormatter={label} minTickGap={55} tickLine={false}/><YAxis width={75} tickFormatter={v=>'$'+Intl.NumberFormat('en',{notation:'compact'}).format(v)} tickLine={false}/><Tooltip labelFormatter={v=>label(Number(v))} formatter={(v,n)=>[price(Number(v),'USD'),n==='value'?'Market value':'Invested capital']}/><Area type="linear" dataKey="value" stroke="#315ce8" fill={`url(#portfolio-${id})`} isAnimationActive={false}/><Line type="stepAfter" dataKey="cost" stroke="#94a3b8" strokeDasharray="5 4" dot={false} isAnimationActive={false}/></ComposedChart></ChartContainer>:<div className="chart-empty">{holdings.length?'History starts on your entered purchase dates. More points will appear as prices update.':'Add shares and purchase costs to see your portfolio chart.'}</div>}
 <p className="portfolio-method">{chart?.method||'Current holdings only. Excludes sold positions, dividends, fees and tax. Value changes can include added capital.'} {list.stocks.some(s=>s.quoteError)&&'Some current quotes are stale; last known prices are used.'}</p>
 {holdings.length>0&&<div className="allocation-strip" aria-label="Holding weights">{holdings.map(s=><span key={s.id}>{s.symbol} <strong>{value?((s.quantity!*s.currentPrice/value)*100).toFixed(1):'0'}%</strong></span>)}</div>}
 </section>;
}
