'use client';
import {useEffect,useState,useId} from 'react';
import {Eye,LockKeyhole,Link2,TrendingUp,ArrowUpRight} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,ReferenceLine,Tooltip,XAxis,YAxis} from 'recharts';
import {ChartContainer} from '@/components/ui/chart';
import {price} from '@/lib/watchlist';
type Row={symbol:string;name:string;companyName:string;date:string;addedPrice:number;currentPrice:number;currency:string;changePercent:number;quoteTime:string};
type ShowcaseData={stocks:Row[];method:string;performance:{startDate:string;initialValue:number;currentValue:number;changePercent:number;investmentPerStock:number;quoteTime:string;points:{time:number;value:number;changePercent:number}[]}};
export function Showcase(){const [data,setData]=useState<ShowcaseData|null>(null),[error,setError]=useState('');const id=useId().replace(/:/g,'');useEffect(()=>{let alive=true,running=false;async function load(){if(running)return;running=true;try{const r=await fetch('/api/showcase');const result=await r.json() as ShowcaseData&{error?:string};if(!r.ok)throw Error(result.error);if(alive){setData(result);setError('');}}catch{if(alive)setError('Market data is temporarily unavailable. Please check back shortly.');}finally{running=false;}}void load();const timer=setInterval(()=>{if(!document.hidden)void load();},60000);return()=>{alive=false;clearInterval(timer);};},[]);
 const performance=data?.performance,up=(performance?.changePercent??0)>=0,color=up?'#14845b':'#c34851';
 return <><div className="hero-preview real-preview expanded-preview"><div className="preview-caption"><span><Eye size={16}/> The long view</span><span className="sample-label">6 companies · Since 2021</span></div><div className="example-column-labels"><span>Company / starting price</span><span>Change / latest price</span></div>{data?data.stocks.map(s=><a className="sample-row" href={'/stocks/'+s.symbol} key={s.symbol}><div className={'sample-symbol symbol-'+s.symbol.toLowerCase()}>{s.symbol}</div><div><strong>{s.name}</strong><small>Sep 3, 2021 · {price(s.addedPrice,s.currency)}</small></div><div className={`sample-return ${s.changePercent>=0?'up':'down'}`}>{s.changePercent>=0?'+':''}{s.changePercent.toLocaleString(undefined,{maximumFractionDigits:2,minimumFractionDigits:2})}%<small>{price(s.currentPrice,s.currency)} now</small></div></a>):<div className="showcase-loading" role="status">{error||'Loading six companies and their story since 2021…'}</div>}<div className="preview-bottom"><span><LockKeyhole size={14}/> Example watchlist · Real prices</span><Link2 size={17}/></div></div>
 <section className="showcase-performance" aria-label="Example watchlist performance since 2021"><div className="showcase-performance-heading"><div><p className="eyebrow">SIX IDEAS. FIVE YEARS OF PERSPECTIVE.</p><h2>Watchlist performance<br className="performance-heading-break"/> since 2021.</h2><p className="performance-subtitle">An equal starting investment. A story that keeps unfolding.</p></div><span className="five-year-badge">5-year view</span></div>{performance?<><div className="showcase-results"><div><span className="performance-label">Since September 3, 2021</span><strong className={`showcase-total ${up?'up':'down'}`}>{up?'+':''}{performance.changePercent.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}%<TrendingUp aria-hidden="true"/></strong><span className="performance-label">{up?'Cumulative gain':'Cumulative loss'} · Illustrative watchlist</span></div><div className="showcase-value-summary"><div><span>Starting value</span><strong>{price(performance.initialValue,'USD')}</strong></div><ArrowUpRight size={22}/><div><span>Latest value</span><strong>{price(performance.currentValue,'USD')}</strong></div></div></div><ChartContainer className="showcase-performance-chart" config={{changePercent:{label:'Watchlist return',color}}}><AreaChart accessibilityLayer data={performance.points} margin={{top:16,left:0,right:8,bottom:4}}><defs><linearGradient id={'showcase-'+id} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity={.22}/><stop offset="1" stopColor={color} stopOpacity={.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e6edf0"/><XAxis dataKey="time" type="number" domain={['dataMin','dataMax']} tickCount={6} minTickGap={40} tickFormatter={v=>String(new Date(v).getFullYear())} axisLine={false} tickLine={false}/><YAxis orientation="right" width={65} tickFormatter={v=>`${v}%`} axisLine={false} tickLine={false}/><ReferenceLine y={0} stroke="#a7b4c3" strokeDasharray="4 4"/><Tooltip labelFormatter={v=>new Date(Number(v)).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})} formatter={v=>[`${Number(v)>=0?'+':''}${Number(v).toFixed(2)}%`,'Watchlist return']} contentStyle={{borderRadius:10,border:'1px solid #dfe8e5'}}/><Area dataKey="changePercent" type="linear" stroke={color} strokeWidth={2.5} fill={`url(#showcase-${id})`} isAnimationActive={false}/></AreaChart></ChartContainer><div className="showcase-performance-foot"><p>{data!.method}<br/>Yahoo Finance · Monthly historical samples plus latest quotes · As of {new Date(performance.quoteTime).toLocaleString()}. Quotes may be delayed.{error&&<><br/><span className="quote-failed">{error} Last loaded data is shown.</span></>}</p><a className="quiet-link" href="/signup">Start your own story <ArrowUpRight size={16}/></a></div></>:<div className="chart-empty" role="status">{error||'Calculating the watchlist’s five-year performance…'}</div>}</section></>;
}
