'use client';
import {StockLink} from './stock-link';
import {useState} from 'react';
import {ArrowUpRight,ArrowDownRight,Minus,Trash2,ChevronLeft,ChevronRight} from 'lucide-react';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Pagination,PaginationContent,PaginationItem} from '@/components/ui/pagination';
import {Button} from '@/components/ui/button';
import {type Stock,price,quoteTime} from '@/lib/watchlist';
export function StocksTable({stocks,onRemove,busy=false}:{stocks:Stock[];onRemove?:(stock:Stock)=>void;busy?:boolean}){
  const [requestedPage,setPage]=useState(1);const pages=Math.max(1,Math.ceil(stocks.length/25));const page=Math.min(requestedPage,pages);const visible=stocks.slice((page-1)*25,page*25);
  return <><Table className="stock-table"><TableHeader><TableRow><TableHead>COMPANY / TICKER</TableHead><TableHead>DATE ADDED</TableHead><TableHead className="numeric">PRICE AT ADD</TableHead><TableHead className="numeric">CURRENT PRICE</TableHead><TableHead className="numeric">CHANGE SINCE ADDED</TableHead>{onRemove&&<TableHead><span className="sr-only">Actions</span></TableHead>}</TableRow></TableHeader><TableBody>{visible.map(stock=>{const change=stock.currentPrice-stock.addedPrice;const pct=change/stock.addedPrice*100;const direction=change>0?'up':change<0?'down':'flat';const Icon=change>0?ArrowUpRight:change<0?ArrowDownRight:Minus;return <TableRow key={stock.id}><TableCell><div className="company-cell"><span className="stock-monogram">{stock.symbol.slice(0,2)}</span><div><StockLink symbol={stock.symbol} name={stock.companyName}/><small>{stock.exchange} · {stock.currency}</small></div></div></TableCell><TableCell><span className="date-added" title={new Date(stock.addedAt).toLocaleString()}>{new Date(stock.addedAt).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</span></TableCell><TableCell className="numeric"><strong className="price-value" title={`Quote at add: ${quoteTime(stock.initialQuoteTime)}`}>{price(stock.addedPrice,stock.currency)}</strong></TableCell><TableCell className="numeric"><strong className={`price-value ${direction}`}>{price(stock.currentPrice,stock.currency)}</strong><span className="quote-time" title={`Last checked: ${quoteTime(stock.checkedAt)}`}>{stock.quoteError?<span className="quote-failed" title={stock.quoteError}>Refresh failed</span>:quoteTime(stock.quoteTime)}</span></TableCell><TableCell className="numeric"><span className={`change-pill ${direction}`}><Icon size={14}/>{change>0?'+':''}{pct.toFixed(2)}%</span><span className={`absolute-change ${direction}`}>{change>0?'+':change<0?'−':''}{price(Math.abs(change),stock.currency)}</span></TableCell>{onRemove&&<TableCell><button className="icon-button remove-stock" aria-label={`Remove ${stock.symbol}`} disabled={busy} onClick={()=>onRemove(stock)}><Trash2 size={16}/></button></TableCell>}</TableRow>;})}</TableBody></Table>
    <div className="table-footer"><span>{stocks.length?`${(page-1)*25+1}–${Math.min(page*25,stocks.length)} of ${stocks.length} stocks`:'0 stocks'}</span>{pages>1?<Pagination className="stock-pagination"><PaginationContent><PaginationItem><Button variant="ghost" size="icon" aria-label="Previous page" disabled={page===1} onClick={()=>setPage(page-1)}><ChevronLeft/></Button></PaginationItem>{Array.from({length:pages},(_,i)=><PaginationItem key={i}><Button variant={page===i+1?'outline':'ghost'} size="icon" aria-current={page===i+1?'page':undefined} onClick={()=>setPage(i+1)}>{i+1}</Button></PaginationItem>)}<PaginationItem><Button variant="ghost" size="icon" aria-label="Next page" disabled={page===pages} onClick={()=>setPage(page+1)}><ChevronRight/></Button></PaginationItem></PaginationContent></Pagination>:<span>Prices may be delayed · Latest regular-session quote</span>}</div></>;
}
