'use client';
import {useT} from "@/components/product/language";
import {LanguageSelect} from '@/components/product/language';
import {T} from '@/components/product/language';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Plus,RefreshCw,Eye,Check,Pencil,Trash2,LoaderCircle,AlertCircle,Share2,Link2,Copy,Mail,LockKeyhole,ArrowUpRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {resolveStockInput} from '@/lib/stock-search.mjs';
import {StockSearch} from '@/components/product/stock-search';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Portfolio} from '@/components/product/portfolio';
import {PerformanceButton} from '@/components/product/performance-button';
import {PositionFields,emptyPosition,type PositionDraft} from '@/components/product/position-fields';
import {WatchlistSummary} from '@/components/product/watchlist-summary';
import {StocksTable} from '@/components/product/stocks-table';
import {Brand} from '@/components/product/nav';
import {apiJson,config} from '@/lib/auth-client';
import {type AccountState,type Stock} from '@/lib/watchlist';
type Action={mode?:'basic'|'advanced';quantity?:number;costPerShare?:number;acquiredAt?:string;notes?:string;action:string;listId?:string;stockId?:string;name?:string;ticker?:string};
export default function Dashboard(){const t=useT();
  const [position,setPosition]=useState<PositionDraft>(emptyPosition),[editing,setEditing]=useState<Stock|null>(null),[editDraft,setEditDraft]=useState<PositionDraft>(emptyPosition);
  const [state,setState]=useState<AccountState|null>(null),[activeId,setActiveId]=useState(''),[ticker,setTicker]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[dialog,setDialog]=useState<'create'|'rename'|'share'|null>(null),[name,setName]=useState(''),[deletion,setDeletion]=useState<{listId:string;stockId?:string;label:string}|null>(null),[configured,setConfigured]=useState<boolean|null>(null);
  const lock=useRef(false),stateRef=useRef<AccountState|null>(null),inputRef=useRef<HTMLInputElement>(null);

  const apply=useCallback((data:AccountState)=>{if(stateRef.current&&Date.parse(data.updatedAt)<Date.parse(stateRef.current.updatedAt))return;stateRef.current=data;setState(data);setActiveId(current=>data.watchlists.some(l=>l.id===current)?current:data.watchlists[0]?.id||'');},[]);
  const load=useCallback(async()=>{try{const settings=await config();setConfigured(settings.authReady);if(!settings.authReady)return;apply(await apiJson<AccountState>('/api/watchlists'));setError('');}catch(e){setError((e as Error).message);}},[apply]);
  const act=useCallback(async(input:Action,automatic=false)=>{if(lock.current){if(automatic)return null;throw new Error('An update is already in progress.');}lock.current=true;setBusy(input.action);if(!automatic){setError('');setNotice('');}try{const data=await apiJson<AccountState>('/api/watchlists',input);apply(data);return data;}catch(e){setError((e as Error).message);throw e;}finally{lock.current=false;setBusy('');}},[apply]);
  useEffect(()=>{void load().then(()=>{if(stateRef.current)void act({action:'refresh'},true).catch(()=>{});});const refresh=()=>{if(!document.hidden&&stateRef.current)void act({action:'refresh'},true).catch(()=>{});};const timer=setInterval(refresh,60000);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',refresh);};},[load,act]);
  useEffect(()=>{
    type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
    const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
    const register=(tool:Tool)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(console.warn);}catch(e){console.warn(e);}};
    register({name:'read_watchlists',description:'Read this signed-in user’s saved watchlists and prices.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>stateRef.current});
    register({name:'add_stock_to_watchlist',description:'Add a stock to a watchlist owned by the signed-in user, within their plan limits.',inputSchema:{type:'object',properties:{listId:{type:'string'},ticker:{type:'string'},quantity:{type:'number',exclusiveMinimum:0}},required:['listId','ticker','quantity'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{const value=input as {listId?:unknown;ticker?:unknown;quantity?:unknown};if(!value||typeof value.listId!=='string'||typeof value.ticker!=='string'||typeof value.quantity!=='number'||!Number.isFinite(value.quantity)||value.quantity<=0)throw new Error('Provide listId, ticker, and a positive quantity.');const result=await act({action:'addStock',listId:value.listId,ticker:value.ticker,quantity:value.quantity});setActiveId(value.listId);return result?.watchlists.find(l=>l.id===value.listId);}});return()=>lifecycle.abort();
  },[act]);
  const active=state?.watchlists.find(l=>l.id===activeId)||state?.watchlists[0];const admin=active?.role==='admin';const stale=active?.stocks.filter(s=>s.quoteError).length||0;
  const shareUrl=active?.shareToken&&typeof window!=='undefined'?`${window.location.origin}/share/${active.shareToken}`:'';
  const addLimited=!!state&&(state.plan.expired||!!active&&active.stocks.length>=state.plan.maxStocks||(state.plan.id==='free'&&active?.id!==state.watchlists[0]?.id));
  async function addStock(e:React.FormEvent){e.preventDefault();if(!active||!ticker.trim())return;try{const symbol=await resolveStockInput(ticker);await act({action:'addStock',listId:active.id,ticker:symbol,...(active.mode==='advanced'?{quantity:Number(position.quantity),costPerShare:position.cost?Number(position.cost):undefined,acquiredAt:new Date(position.date+'T00:00:00').toISOString(),notes:position.notes}:{})});setNotice(`${ticker} added.`);setTicker('');setPosition(emptyPosition());inputRef.current?.focus();}catch(e){setError((e as Error).message);}}
  async function saveList(e:React.FormEvent){e.preventDefault();if(!active)return;try{const result=await act({action:dialog==='create'?'createList':'renameList',listId:active.id,name,mode:'advanced'});if(dialog==='create'&&result){const created=result.watchlists.find(l=>!state?.watchlists.some(old=>old.id===l.id));if(created)setActiveId(created.id);}setDialog(null);}catch{}}
  async function savePosition(e:React.FormEvent){e.preventDefault();if(!active||!editing)return;try{await act({action:'initializePosition',listId:active.id,stockId:editing.id,quantity:Number(editDraft.quantity),costPerShare:Number(editDraft.cost),acquiredAt:new Date(editDraft.date+'T00:00:00').toISOString(),notes:editDraft.notes});setEditing(null);}catch{}}
  async function remove(){if(!deletion)return;try{await act({action:deletion.stockId?'removeStock':'deleteList',listId:deletion.listId,stockId:deletion.stockId});setDeletion(null);}catch{}}
  async function copy(){try{await navigator.clipboard.writeText(shareUrl);setNotice('Link copied.');}catch{setNotice('Select and copy the link above.');}}
  return <><header className="topbar"><Brand/><div className="account-nav"><a className="plan-badge" href="/pricing">{state?.plan.id==='pro'?'PRO':'BASIC'}</a><a href="/account">{state?.user.isAdmin?'Admin account':t("Account")}</a><span className="save-state">{busy?<LoaderCircle size={15} className="spin"/>:<Check size={15}/>} {busy?t("Updating…"):state?t("Saved to your account"):t("Connecting…")}</span></div></header>
  <main className="workspace"><div className="page-heading dashboard-heading"><div><p className="eyebrow">YOUR INVESTING SPACE</p><h1><T text="Watchlists"/></h1><p className="intro"><T text="Keep your ideas close. Follow how they grow."/></p>{state&&<div className="workspace-summary"><span className="workspace-plan">{state.plan.id==='pro'?'Pro':t("Basic")}</span><span><strong>{state.watchlists.length}</strong> / {state.plan.maxLists} watchlists</span><span>Up to <strong>{state.plan.maxStocks}</strong> stocks per list</span></div>}</div><div className="heading-actions"><Button variant="outline" className="outline-button" disabled={!active||!!busy} onClick={()=>{setError('');setNotice('');setDialog('share');}}><Share2/><T text="Invite a friend"/></Button><Button className="primary-button" disabled={!state||!!busy} onClick={()=>{setName('');setError('');setDialog('create');}}><Plus/><T text="New watchlist"/></Button></div></div>
  {configured===false?<div className="watch-card"><Empty className="empty-watchlist"><LockKeyhole size={32}/><EmptyTitle className="empty-title">Your account workspace is almost ready</EmptyTitle><EmptyDescription>Account setup is still in progress. Once connected, sign in to create private lists and share them with friends.</EmptyDescription><a className="solid-link" href="/">Back to welcome</a></Empty></div>:<>
  {error&&!dialog&&!deletion&&!editing&&<div role="alert" className="error-banner"><AlertCircle size={18}/>{error}<Button variant="ghost" onClick={()=>void load()}>Retry</Button></div>}
  {state?.plan.expired&&<div className="quote-warning">Your free trial has ended. Your saved lists remain available. <a href="/pricing">Upgrade to add more stocks →</a></div>}
  <span className="sr-only" role="status">{notice}</span>{state?.user.local&&<p className="local-workspace-note">Saved on this Mac · Private workspace</p>}
  {state&&active?<Tabs value={active.id} onValueChange={v=>{setActiveId(String(v));setTicker('');setError('');}}><div className="tab-strip"><TabsList variant="line" aria-label={t("Watchlists")}>{state.watchlists.map(l=><TabsTrigger key={l.id} value={l.id}>{l.name}<span className="tab-count">{l.stocks.length}</span></TabsTrigger>)}</TabsList></div><TabsContent key={active.id} value={active.id}><section className="watch-card"><div className="card-heading"><div><div className="list-title"><h2>{active.name}</h2><span className="owner-label">{active.mode==='advanced'?'Advanced · ':''}{admin?t("Owner"):t("Viewer")}</span>{admin&&<><button className="icon-button" aria-label="Rename watchlist" disabled={!!busy} onClick={()=>{setName(active.name);setError('');setDialog('rename');}}><Pencil size={14}/></button>{state.watchlists.length>1&&<button className="icon-button" aria-label="Delete watchlist" disabled={!!busy} onClick={()=>{setError('');setDeletion({listId:active.id,label:active.name});}}><Trash2 size={14}/></button>}</>}</div><p>{active.mode==='advanced'?'Track your holdings, cost basis, and the bigger picture.':'Track performance from the day you add a stock.'}</p></div><div className="card-tools"><span className="refresh-state"><span className={`status-dot ${stale?'warning-dot':''}`}/>{busy==='refresh'?t("Refreshing…"):t("Refreshes every 60s")}</span><Button variant="outline" disabled={!!busy} onClick={()=>{setError('');setNotice('');setDialog('share');}}><Link2/><T text="Share"/></Button></div></div>
  <div className="watchlist-compose-row">{admin&&<form className={`add-bar ${active.mode==='advanced'?'advanced-add-bar':''}`} onSubmit={addStock}><StockSearch value={ticker} onChange={setTicker} inputRef={inputRef}/><Button type="submit" className="primary-button" disabled={!!busy||!ticker.trim()||addLimited}>{busy==='addStock'?<LoaderCircle className="spin"/>:<Plus/>}{busy==='addStock'?t("Adding…"):t("Add stock")}</Button><Button type="button" variant="outline" className="refresh-button" disabled={!!busy} onClick={()=>void act({action:'refresh'}).catch(()=>{})}><RefreshCw className={busy==='refresh'?'spin':''}/><T text="Refresh"/></Button>{active.mode==='advanced'&&<PositionFields value={position} onChange={setPosition}/>}</form>}<WatchlistSummary list={active}/></div>
  {addLimited&&<div className="quote-warning">This list has reached your plan’s limit. <a href="/pricing">View plans →</a></div>}{stale>0&&<div className="quote-warning" role="status">{stale} quotes could not be refreshed. Last known prices are shown.</div>}



  {active.stocks.length?<div className="watchlist-analytics-layout"><div className="watchlist-table-pane"><StocksTable actions={<PerformanceButton list={active} version={state.updatedAt}/>} key={active.id} stocks={active.stocks} advanced={active.mode==='advanced'} onEdit={admin?(stock:Stock)=>{setError('');setEditing(stock);setEditDraft({quantity:String(stock.quantity||100),cost:String(stock.costPerShare||stock.addedPrice),date:(stock.acquiredAt||stock.addedAt).slice(0,10),notes:stock.notes});}:undefined} busy={!!busy} onRemove={admin?(stock:Stock)=>{setError('');setDeletion({listId:active.id,stockId:stock.id,label:stock.symbol});}:undefined}/></div><aside className="watchlist-chart-pane"><Portfolio list={active} version={state.updatedAt}/></aside></div>:<><div className="column-preview"><span><T text="COMPANY / TICKER"/></span><span><T text="DATE ADDED"/></span><span><T text="PRICE AT ADD"/></span><span><T text="CURRENT PRICE"/></span><span>CHANGE</span></div><Empty className="empty-watchlist"><div className="empty-icon"><Eye size={27}/></div><EmptyHeader><EmptyTitle className="empty-title"><T text="Your next idea starts here"/></EmptyTitle><EmptyDescription>Add your first stock above. We’ll remember its starting price and follow what happens next.</EmptyDescription></EmptyHeader><div className="ticker-hints">Try {['CRDO','AAPL','MSFT'].map(s=><button key={s} onClick={()=>{setTicker(s);inputRef.current?.focus();}}>{s}</button>)}</div></Empty></>}
  </section></TabsContent></Tabs>:<Empty className="empty-watchlist"><LoaderCircle className="spin"/><EmptyTitle>Opening your watchlists…</EmptyTitle></Empty>}
  </>}
  <footer className="workspace-footer"><LanguageSelect/><span>Yahoo Finance · Quotes may be delayed</span><span>Only list admins can edit · <a href="/privacy"><T text="Privacy"/></a></span></footer></main>
  <Dialog open={dialog==='create'||dialog==='rename'} onOpenChange={v=>{if(!v&&!busy)setDialog(null);}}><DialogContent className="list-dialog"><DialogTitle>{dialog==='create'?t("New watchlist"):'Rename watchlist'}</DialogTitle><DialogDescription>{state&&dialog==='create'&&state.watchlists.length>=state.plan.maxLists?(state.plan.id==='pro'?`You’ve reached your limit of ${state.plan.maxLists} watchlists. Delete a watchlist to create another.`:'You’ve used all the watchlists in your plan. Upgrade to Pro for up to 10.'):'Keep your ideas together with a name that makes sense to you.'}</DialogDescription>{state&&dialog==='create'&&state.watchlists.length>=state.plan.maxLists?(state.plan.id==='pro'?<Button className="primary-button dialog-submit" onClick={()=>setDialog(null)}><T text="Back to watchlists"/></Button>:<a className="solid-link" href="/pricing">View plans <ArrowUpRight size={16}/></a>):<form onSubmit={saveList}><label className="form-label" htmlFor="list-name"><T text="Watchlist name"/></label><p className="field-note">Every watchlist includes quantities, costs and portfolio performance.</p><Input id="list-name" autoFocus maxLength={60} required value={name} onChange={e=>setName(e.target.value)}/>{error&&<p role="alert" className="form-error">{error}</p>}<Button type="submit" className="primary-button dialog-submit" disabled={!!busy||!name.trim()}><T text="Save watchlist"/></Button></form>}</DialogContent></Dialog>
  <Dialog open={dialog==='share'} onOpenChange={v=>{if(!v&&!busy)setDialog(null);}}><DialogContent className="list-dialog"><DialogTitle>Good ideas are better together</DialogTitle><DialogDescription>Anyone with this link can view “{active?.name}”, including its starting prices, performance, share quantities, purchase costs and notes. Only you can edit. You can turn sharing off at any time.</DialogDescription>{state?.user.local&&<p className="setup-notice">No login is needed to view this link. This local address works only on this computer; sharing with friends on other devices requires deployment.</p>}{shareUrl?<><label className="form-label" htmlFor="share-link">Read-only share link</label><Input id="share-link" readOnly value={shareUrl} onFocus={e=>e.target.select()}/><div className="share-actions"><Button className="primary-button" onClick={()=>void copy()}><Copy/>Copy link</Button><a className="email-invite" href={`mailto:?subject=${encodeURIComponent('Take a look at my watchlist')}&body=${encodeURIComponent(`Here’s what I’m watching: ${shareUrl}`)}`}><Mail size={16}/>Invite by email</a></div><Button variant="ghost" className="revoke-button" disabled={!!busy} onClick={()=>{if(active)void act({action:'revokeShare',listId:active.id}).then(()=>setNotice('Sharing turned off. The old link no longer works.')).catch(()=>{});}}>Turn off sharing</Button></>:<Button className="primary-button" disabled={!!busy||!admin} onClick={()=>{if(active)void act({action:'shareList',listId:active.id}).catch(()=>{});}}><Link2/>Create share link</Button>}{notice&&<p role="status" className="share-notice">{notice}</p>}{error&&<p role="alert" className="form-error">{error}</p>}</DialogContent></Dialog>
  <Dialog open={!!editing} onOpenChange={v=>{if(!v&&!busy)setEditing(null);}}><DialogContent className="position-dialog"><DialogTitle>Set {editing?.symbol} quantity</DialogTitle><DialogDescription>This stock was added before quantities were available. Set its quantity once. Shares and purchase details cannot be changed after saving.</DialogDescription><form onSubmit={savePosition}><PositionFields value={editDraft} onChange={setEditDraft} editing/>{error&&<p role="alert" className="form-error">{error}</p>}<Button className="primary-button dialog-submit" disabled={!!busy}>Save fixed quantity</Button></form></DialogContent></Dialog>
  <AlertDialog open={!!deletion} onOpenChange={v=>{if(!v&&!busy)setDeletion(null);}}><AlertDialogContent><AlertDialogTitle>Remove {deletion?.label}?</AlertDialogTitle><AlertDialogDescription>This removes {deletion?.stockId?'the stock and its starting price':'the watchlist, its stocks, and its share link'} from your account.</AlertDialogDescription>{error&&<p role="alert" className="form-error">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={!!busy}>Keep it</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={!!busy} onClick={()=>void remove()}>{busy?'Removing…':'Remove'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </>;
}
