'use client';
import {useT} from "@/components/product/language";
import {T} from '@/components/product/language';
import {use,useEffect,useState} from 'react';
import {ArrowUpRight,ArrowDownRight,Plus,Maximize2,RefreshCw,LoaderCircle,Building2,Moon,Star} from 'lucide-react';
import {PublicNav,PublicFooter} from '@/components/product/nav';
import {PositionFields,emptyPosition,type PositionDraft} from '@/components/product/position-fields';
import {PriceChart,type ChartStyle} from '@/components/product/price-chart';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';

import {EarningsStory,StockFactsRail} from '@/components/product/earnings-story';
import {marketChart,stockDataFetch,type MarketChart} from '@/lib/market';
import {chartPeriodStats,rangeLabel} from '@/lib/chart-period.mjs';
import {price,quoteTime,type AccountState} from '@/lib/watchlist';
import {apiJson,signedIn as hasAccount} from '@/lib/auth-client';
import {track} from '@/lib/analytics';
import {applyGuestAction,ensureGuestList,writeGuestState} from '@/lib/guest-watchlist.mjs';
import {parseCurrencyMismatch} from '@/lib/portfolio-currency.mjs';
import {MarketLockBanner} from '@/components/product/market-lock-banner';
type Fundamentals={available:boolean;companyName?:string;description?:string;sector?:string;industry?:string;website?:string;employees?:number;country?:string;marketCap?:number;revenue?:number;netIncome?:number;eps?:number;shares?:number;pe?:number;forwardPe?:number;dividendRate?:number;dividendYield?:number;exDividendDate?:string;beta?:number;analysts?:string;targetPrice?:number;earningsDate?:string;postMarketPrice?:number;postMarketTime?:string;fetchedAt?:string;error?:string};
const ranges=[['1d','1D'],['5d','5D'],['1mo','1M'],['3mo','3M'],['6mo','6M'],['ytd','YTD'],['1y','1Y'],['5y','5Y'],['max','Max']];
const compact=(v:number|undefined)=>v===undefined?'—':new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:2}).format(v);
const num=(v:number|undefined)=>v===undefined?'—':v.toLocaleString(undefined,{maximumFractionDigits:2});
export default function StockDetails({params}:{params:Promise<{symbol:string}>}){const t=useT();
  const [position,setPosition]=useState<PositionDraft>(emptyPosition);
  const {symbol:raw}=use(params);const symbol=raw.toUpperCase();const [range,setRange]=useState('1d'),[chartStyle,setChartStyle]=useState<ChartStyle>('line'),[chart,setChart]=useState<MarketChart|null>(null),[overview,setOverview]=useState<MarketChart|null>(null),[fund,setFund]=useState<Fundamentals|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[full,setFull]=useState(false),[adding,setAdding]=useState(false),[account,setAccount]=useState<AccountState|null>(null),[listId,setListId]=useState(''),[addError,setAddError]=useState(''),[saving,setSaving]=useState(false),[saved,setSaved]=useState(''),[version,setVersion]=useState(0),[favorite,setFavorite]=useState(false),[signedIn,setSignedIn]=useState(false),[savingFavorite,setSavingFavorite]=useState(false),[rail,setRail]=useState(true);
  useEffect(()=>{let alive=true;setBusy(true);setError('');void marketChart(symbol,range).then(data=>{if(alive){setChart(data);if(range==='1d')setOverview(data);}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setBusy(false);});return()=>{alive=false;};},[symbol,range,version]);
  useEffect(()=>{let alive=true;void marketChart(symbol,'1d').then(data=>{if(alive)setOverview(data);}).catch(()=>{});const timer=setInterval(()=>{if(!document.hidden)setVersion(v=>v+1);},60000);return()=>{alive=false;clearInterval(timer);};},[symbol,version]);
  useEffect(()=>{let alive=true;void stockDataFetch('/api/stocks/'+encodeURIComponent(symbol)+'/fundamentals').then(async r=>{const value=await r.json() as Fundamentals;if(alive)setFund(value);}).catch(()=>{if(alive)setFund({available:false});});return()=>{alive=false;};},[symbol]);
  const [quarterEnds,setQuarterEnds]=useState<string[]>([]);
  useEffect(()=>{let alive=true;void stockDataFetch('/api/stocks/'+encodeURIComponent(symbol)+'/earnings').then(async r=>{const value=await r.json() as {quarters?:{periodEnd:string}[]};if(alive)setQuarterEnds((value.quarters||[]).map(q=>q.periodEnd).filter(Boolean));}).catch(()=>{if(alive)setQuarterEnds([]);});return()=>{alive=false;};},[symbol]);
  useEffect(()=>{let alive=true;void apiJson<{signedIn:boolean;favorites:{symbol:string}[]}>('/api/favorites',undefined,false).then(result=>{if(!alive)return;setSignedIn(!!result.signedIn);setFavorite(!!result.favorites?.some(row=>row.symbol===symbol));}).catch(()=>{if(alive){setSignedIn(false);setFavorite(false);}});return()=>{alive=false;};},[symbol]);
  const data=overview||chart;const period=chart&&chart.range===range?chartPeriodStats(chart):null;const change=period?.changePercent??data?.quote.changePercent;const dollar=period?.change??data?.quote.change;const direction=change!==null&&change!==undefined&&change<0?'down':'up';const ChangeIcon=direction==='down'?ArrowDownRight:ArrowUpRight;
  async function openAdd(){setAdding(true);setAddError('');setSaved('');try{if(await hasAccount()){const result=await apiJson<AccountState>('/api/watchlists');setAccount(result);setListId(result.watchlists[0]?.id||'');return;}const guest=ensureGuestList(window.localStorage);setAccount(guest);setListId(guest.watchlists[0].id);}catch(e){setAddError((e as Error).message);}}
  async function toggleFavorite(){if(!signedIn){window.location.assign('/signup');return;}const next=!favorite;setFavorite(next);setSavingFavorite(true);try{const result=await apiJson<{signedIn:boolean;favorites:{symbol:string}[]}>('/api/favorites',{symbol,favorite:next});setSignedIn(true);setFavorite(!!result.favorites?.some(row=>row.symbol===symbol));}catch(e){setFavorite(!next);setError((e as Error).message);}finally{setSavingFavorite(false);}}
  async function add(){setSaving(true);setAddError('');try{if(account?.guest){const firstStock=!account.watchlists.some(list=>list.stocks.length);const chart=await marketChart(symbol);const quote={symbol:chart.symbol,companyName:chart.companyName,currency:chart.currency,exchange:chart.exchange,price:chart.quote.price,quoteTime:chart.quote.quoteTime||chart.fetchedAt,checkedAt:chart.fetchedAt};const result=writeGuestState(applyGuestAction(account,{action:'addStock',listId,ticker:symbol,quantity:Number(position.quantity),costPerShare:position.cost?Number(position.cost):quote.price,acquiredAt:new Date(position.date+'T00:00:00').toISOString(),notes:position.notes},quote),window.localStorage);setAccount(result);setSaved(`${symbol} was added with the latest available price.`);if(firstStock)track('watchlist_created');return;}const result=await apiJson<AccountState>('/api/watchlists',{action:'addStock',listId,ticker:symbol,...(account?.watchlists.find(l=>l.id===listId)?.mode==='advanced'?{quantity:Number(position.quantity),costPerShare:position.cost?Number(position.cost):undefined,acquiredAt:new Date(position.date+'T00:00:00').toISOString(),notes:position.notes}:{})});setAccount(result);setSaved(`${symbol} was added with the latest available price.`);}catch(e){setAddError((e as Error).message);}finally{setSaving(false);}}
  const leftMetrics:[string,string][]=[[t("Market cap"),compact(fund?.marketCap)],[t("Revenue (TTM)"),compact(fund?.revenue)],[t("Net income"),compact(fund?.netIncome)],[t("EPS"),num(fund?.eps)],[t("Shares outstanding"),compact(fund?.shares)],[t("P/E ratio"),num(fund?.pe)],[t("Forward P/E"),num(fund?.forwardPe)],[t("Dividend yield"),fund?.dividendYield===undefined?'—':(fund.dividendYield*100).toFixed(2)+'%'],[t("Ex-dividend date"),fund?.exDividendDate?new Date(fund.exDividendDate).toLocaleDateString():'—']];
  const rightMetrics:[string,string][]=[[t("Volume"),data?.quote.volume===null||!data? '—':compact(data.quote.volume)],[t("Open"),data?.quote.open==null?'—':price(data.quote.open,data.currency)],[t("Previous close"),data?.quote.previousClose==null?'—':price(data.quote.previousClose,data.currency)],[t("Day’s range"),data?.quote.dayLow==null||data.quote.dayHigh==null?'—':`${data.quote.dayLow.toFixed(2)} – ${data.quote.dayHigh.toFixed(2)}`],[t("52-week range"),data?.quote.fiftyTwoWeekLow==null||data.quote.fiftyTwoWeekHigh==null?'—':`${data.quote.fiftyTwoWeekLow.toFixed(2)} – ${data.quote.fiftyTwoWeekHigh.toFixed(2)}`],[t("Beta"),num(fund?.beta)],[t("Analyst consensus"),fund?.analysts?fund.analysts.replace(/_/g,' '):'—'],[t("Price target"),fund?.targetPrice===undefined||!data?'—':price(fund.targetPrice,data.currency)],[t("Next Earnings Date"),fund?.earningsDate?new Date(fund.earningsDate).toLocaleDateString():'—']];
  const rangeControls=<Tabs value={range} onValueChange={v=>setRange(String(v))}><TabsList className="chart-ranges" aria-label="Chart time range">{ranges.map(([value,label])=><TabsTrigger key={value} value={value}>{label}</TabsTrigger>)}</TabsList></Tabs>;
  const styleControls=<Tabs value={chartStyle} onValueChange={v=>setChartStyle(v as ChartStyle)}><TabsList className="chart-ranges chart-style-toggle" aria-label="Chart type"><TabsTrigger value="line">{t("Line")}</TabsTrigger><TabsTrigger value="candle">{t("Candle")}</TabsTrigger></TabsList></Tabs>;
  const facts:[string,string][]=[...leftMetrics,...rightMetrics];
  const eventDates=chart?.earningsDates?.length?chart.earningsDates:quarterEnds;
  return <><PublicNav/><main className="stock-detail-page"><div className="stock-back-row"><a className="stock-back" href="/dashboard">{t("← Markets")}</a><a className="stock-back" href="/earnings">{t("Earnings calendar")}</a></div><div className="stock-summary-card"><div className="detail-title-row"><div className="company-title-block"><div className="company-name-line"><h1>{data?.companyName||symbol} <span>({symbol})</span></h1><details className="company-about"><summary><Building2 size={14}/> {t("About company")}</summary><div className="company-about-content"><h2>{data?.companyName||symbol}</h2><p>{fund?.description||'A company description is not currently available.'}</p><dl><div><dt>{t("Sector")}</dt><dd>{fund?.sector||'—'}</dd></div><div><dt>{t("Industry")}</dt><dd>{fund?.industry||'—'}</dd></div><div><dt>{t("Employees")}</dt><dd>{num(fund?.employees)}</dd></div><div><dt>{t("Country")}</dt><dd>{fund?.country||'—'}</dd></div></dl>{fund?.website&&/^https?:\/\//.test(fund.website)&&<a href={fund.website} target="_blank" rel="noreferrer">{t("Company website ↗")}</a>}</div></details></div><p>{data?`${data.exchange} · ${data.currency}`:'Stock details'}</p></div><div className="heading-actions"><Button variant="outline" className={'outline-button favorite-action'+(favorite?' is-on':'')} title={favorite?t("Favorited"):t("Favorite")} disabled={savingFavorite} onClick={()=>void toggleFavorite()}><Star size={16} fill={favorite?'currentColor':'none'}/>{favorite?t("Favorited"):t("Favorite")}</Button><Button variant="outline" className="outline-button" disabled={!chart} onClick={()=>setFull(true)}><Maximize2/><T text="Full chart"/></Button><Button className="primary-button" onClick={()=>void openAdd()}><Plus/>{t("Add to watchlist")}</Button></div></div>{data&&<div className="detail-prices"><div><div className="detail-price"><strong>{price(data.quote.price,data.currency)}</strong>{change!==null&&change!==undefined&&<span className={direction}><ChangeIcon size={21}/>{dollar!=null&&Number.isFinite(dollar)?`${dollar>=0?'+':''}${dollar.toFixed(2)} `:''}({change>=0?'+':''}{change.toFixed(2)}%)</span>}</div><p>{range==='1d'?`Regular session · ${data.quote.quoteTime?quoteTime(data.quote.quoteTime):'Time unavailable'}`:`${rangeLabel(range)} change · ${data.quote.quoteTime?quoteTime(data.quote.quoteTime):'Time unavailable'}`}</p></div>{fund?.postMarketPrice!==undefined&&<div className="postmarket"><strong>{price(fund.postMarketPrice,data.currency)}</strong><p><Moon size={13}/>After hours · {fund.postMarketTime?quoteTime(fund.postMarketTime):'Time unavailable'}</p></div>}</div>}</div>{error&&<div className="error-banner" role="alert">{error}<Button variant="ghost" onClick={()=>setVersion(v=>v+1)}>Retry</Button></div>}
  <div className={'stock-happening'+(rail?'':' is-collapsed')}>
    <div className="stock-happening-main">
      <EarningsStory symbol={symbol} nextDate={fund?.earningsDate}/>
      <section className="story-card company-story">
        <p className="eyebrow"><T text="COMPANY"/></p>
        <h2>{data?.companyName||symbol}</h2>
        <p>{fund?.description||t('A company description is not currently available.')}</p>
        <dl className="company-facts">{[[t("Sector"),fund?.sector],[t("Industry"),fund?.industry],[t("Employees"),fund?.employees===undefined?undefined:num(fund.employees)],[t("Country"),fund?.country]].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{value||'—'}</dd></div>)}</dl>
        {fund?.website&&/^https?:\/\//.test(fund.website)&&<a href={fund.website} target="_blank" rel="noreferrer">{t("Company website ↗")}</a>}
      </section>
      <section className="main-chart-panel story-card">
        <div className="chart-toolbar">{styleControls}{rangeControls}<Button variant="ghost" size="icon" aria-label="Refresh stock chart" disabled={busy} onClick={()=>setVersion(v=>v+1)}><RefreshCw className={busy?'spin':''}/></Button></div>
        <div className="chart-stage" aria-busy={busy}>{chart&&chart.range===range?<PriceChart data={chart} style={chartStyle} eventDates={eventDates}/>:<div className="chart-empty"><LoaderCircle className="spin"/>{t("Loading chart…")}</div>}</div>
        <div className="chart-caption"><span>{range==='1d'?`Latest session: ${chart?.sessionDate||'—'}`:t('Historical price · Split-adjusted close')}{!!eventDates.length&&range!=='1d'&&` · ${t('Red lines mark past earnings reports.')}`}</span><span>{chart?.timezone}</span></div>
      </section>
    </div>
    <StockFactsRail open={rail} onToggle={()=>setRail(v=>!v)} facts={facts} note={fund?.available?t('Company fundamentals. Reporting periods vary.')+' “—” '+t('means unavailable.'):t('Some company statistics are unavailable from the provider.')}/>
  </div><footer className="workspace-footer"><span>Yahoo Finance · Quotes may be delayed · Refreshes every 60 seconds</span><span>Current price vs previous close; watchlist returns use your price at add.</span></footer></main><PublicFooter/>
  <Dialog open={full} onOpenChange={setFull}><DialogContent className="full-chart-dialog"><DialogTitle>{symbol} — Price chart</DialogTitle><DialogDescription>{chart?.sessionDate} · {data?.currency} · {chart?.timezone}</DialogDescription>{styleControls}{rangeControls}{chart&&chart.range===range?<PriceChart data={chart} style={chartStyle} eventDates={eventDates}/>:<p>Loading chart…</p>}</DialogContent></Dialog>
  <Dialog open={adding} onOpenChange={v=>{if(!saving)setAdding(v);}}><DialogContent className="list-dialog stock-add-dialog"><DialogTitle>Add {symbol} to a watchlist</DialogTitle><DialogDescription>Choose a watchlist and add your purchase details. Leave cost blank to use the latest quote.</DialogDescription>{account&&<form onSubmit={e=>{e.preventDefault();void add();}}><label className="watchlist-select-label">Watchlist</label><Select value={listId} onValueChange={v=>setListId(String(v))}><SelectTrigger className="stock-list-select" aria-label="Watchlist"><SelectValue>{account.watchlists.find(l=>l.id===listId)?.name}</SelectValue></SelectTrigger><SelectContent>{account.watchlists.map(l=><SelectItem key={l.id} value={l.id}>{l.name} ({l.stocks.length}/{account.plan.maxStocks})</SelectItem>)}</SelectContent></Select>{account.watchlists.find(l=>l.id===listId)?.mode==='advanced'&&<PositionFields value={position} onChange={setPosition} currency={account.watchlists.find(l=>l.id===listId)?.stocks[0]?.currency||'USD'}/>}<Button type="submit" className="primary-button" disabled={saving||!listId}>{saving?<LoaderCircle className="spin"/>:<Plus/>}Add stock</Button></form>}{addError&&(parseCurrencyMismatch(addError)?<MarketLockBanner message={addError}/>:<p className="form-error" role="alert">{addError}</p>)}{saved&&<p className="share-notice" role="status">{saved} <a href="/watchlists">Open watchlists →</a></p>}</DialogContent></Dialog></>;
}
